### ISSUE TITLE
DesktopBridgeToUWP 

### ISSUE THREAD

**Issue by ThanawutZiios** [Microsoft/DesktopBridgeToUWP-Samples#1]
Hi,

Thank you for your sample code , is there any code/knowledge on how to do DesktopBridge on javascript version? My code is on hosted web app and want to call Desktop App to get data.

Right now what I do is set appService to be StartPage="js/appservice.js"
and after UWP ( index.html ) call to Desktop via launchFullTrustProcessForCurrentAppAsync it open WPF App , after that WPF app call back on AppServiceConnection and open the connection to UWP App on StartPage ( appservice.js ) but my deadend here since my index.html cannot get anything from appservice.js , even in appservice.js show messagebox that come from WPF it still not show.
Did I missing some concept or how I can make it work

Thank you,
Tour

**Comment by vladimp** [comment]
Hi Tour,

Thanks for reporting the issue.
One thing you can try is adding the following to the manifest:
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>UWP.dll</Path>
        <ActivatableClass ActivatableClassId="CommunicationAppService.MyService" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>

We will work to add a javascript sample in future.

Thanks,
Vladimir

**Comment by cconner100** [comment]
You have closed this issue but I don't see a resolution? any suggestions?
