### ISSUE TITLE
VS 2015 error when opening DesktopBridgeDemoStep solutions

### ISSUE THREAD

**Issue by TeTiga** [Microsoft/DesktopBridgeToUWP-Samples#10]
Got error when loading Step 1:
"Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - UWPPackager, "E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step1\UWPPackager\UWPPackager.vsdproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - MyDesktopApp, "E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step1\MyDesktopApp\MyDesktopApp.csproj"
	 - DesktopBridgeDemoStep1, "E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step1\DesktopBridgeDemoStep1.sln"

Trying Step 4 I get:
E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step4\BackgroundTasks\BackgroundTasks.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step4\BackgroundTasks\BackgroundTasks.csproj

E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step4\MyUWPApp\MyUWPApp.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step4\MyUWPApp\MyUWPApp.csproj

E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step4\BackgroundTasks\BackgroundTasks.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\work\GitHub\DesktopBridgeToUWP-Samples\Samples\JourneyAcrossTheBridge\DesktopBridgeDemo - Step4\BackgroundTasks\BackgroundTasks.csproj

**Comment by AddressXception** [comment]
check your solution file and see if VS 2015 changed the project template type.  The standard is 

FAE04EC0-301F-11D3-BF4B-00C04F79EFBC 

but the bridge projects use a template type of:

F365BE41E-7993-430D-A5E6-1381A54BC077

In my experience VS 2015 will let you open the project and modify files, but it will change the template type in the solution.  You have to use VS 15 Preview 2 or greater to actually debug deploy, since that is what the project template VSIX  supports. 

Did you follow these steps?

https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-deploy-and-debug?f=255&MSPPError=-2147217396

**Comment by TeTiga** [comment]
I already hat the suspicion that VS 15 has to be used. But in the Readme of Desktop app bridge to UWP Samples only Visual Studio 2015 if given as requirement.
When using VS 15 Preview 4 and changing Versions in MyUWPApp.csproj to 10.0.14393.0  it worked now for me.
