### ISSUE TITLE
AppServiceBridgeSample closes UWP if Win32 app is closed

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/DesktopBridgeToUWP-Samples#11]
In the AppServiceBridge sample, the win32 app, if shut down, will cause the UWP app to shut down.  That isn't desired.  How can this dependency be avoided?
1. Start UWP app
2. Start Win32 process 
3. Win32 process connects to UWP app
4. Close Win32 process
5. UWP shuts down a few seconds later without suspending. (How can we avoid this) 

Thanks,
Michael

**Comment by vladimp** [comment]
Hi Michael,

Thanks for reporting the issue. I checked in the fix.
I associated a cancellation handler with the background task to avoid the UWP process to shut down when the background task is canceled.

Thanks,
Vlad
