### ISSUE TITLE
My VS2015 unable to open UWPPackager Project.

### ISSUE THREAD

**Issue by jigneshdesai** [Microsoft/DesktopBridgeToUWP-Samples#14]
Hi 
My VS2015 unable to open UWPPackager Project.   Says  "Incompatible"
Please Guide.

**Comment by vladimp** [comment]
Thanks for the feedback!
Please make sure you installed the desktop to UWP packaging project - https://visualstudiogallery.msdn.microsoft.com/c71521f1-3c73-49e8-b1a4-70e958f179ba
I will clarify the documentation.

Thanks!
Vlad

**Comment by vladimp** [comment]
I hope it resolved your issue, I will close this case for now.
Please let me know if you have any further questions.

Thanks,
Vlad
