### ISSUE TITLE
non-plated taskbar icons

### ISSUE THREAD

**Issue by rednoah** [Microsoft/DesktopBridgeToUWP-Samples#15]
Are there any known issues with unplated / *_altform-unplated.png icons (or in general scaled resources) for Windows Bridge apps?

Scaled (e.g. *.scale-100.png) resources seem to get fully ignored for my Desktop Bridge app even though it works fine UWP apps.

**Comment by wjk** [comment]
Yeah, I‘ve seen this too. It’s puzzling. @vladimp Could you please take a look at this? I can workaround this by using non-scaled resources during development, but of course this won’t work for release. Any pointers? Thanks!

**Comment by ArianGhotbi** [comment]
Hi @rednoah & @wjk ,
Apologies for the delay here.
There are no known issues with unplated assets.

I'm not sure which documentation you used, but below is the set of instructions that will make the unplated assets work properly. If there is documentation out there that is incorrect, please let us know so we can correct it.

**Note**: This guide is specifically for the 44x44 assets that show up on the taskbar
 
1.	First obtain the correct 44x44 images and copy them into the folder that contains your images (i.e. Assets).
 
2.	For every 44x44, you need to create a copy of the image in the same folder and append: “**.targetsize-44_altform-unplated**” to the filename
a.	i.e. MYAPP_44x44.png (note: this is the icon referenced in the appxmanifest under VisualElements attribute: Square44x44Logo)
b.	i.e. MYAPP_44x44.targetsize-44_altform-unplated.png
c.	You need to have 2 copies of each icon, just named in a specific way
 
3.	In the AppXManifest, for every icon that you are fixing, you need to set the BackgroundColor to transparent 
a.	this attribute can be found under VisualElements for each application)
<Application Id="MYAPP" Executable="MYAPP.exe" EntryPoint="Windows.FullTrustApplication">
<uap:VisualElements 
DisplayName="MYAPP" 
Description="No description entered." 
BackgroundColor="transparent" 
Square44x44Logo="Assets\MYAPP_44x44.png" 
Square150x150Logo="Assets\MYAPP_150x150.png" />
 
4.	Open CMD, change directory to the package’s root folder, and create a priconfig.xml file:
a.	makepri createconfig /cf priconfig.xml /dq en-US
 
5.	Using CMD, staying in the package’s root folder, create the resources.pri file(s):
a.	makepri new /pr <PHYSICAL_PATH_TO_FOLDER> /cf <PHYSICAL_PATH_TO_FOLDER>\priconfig.xml
b.	Example: makepri new /pr c:\MYAPP /cf c:\MYAPP\priconfig.xml
 
6.	Pack as AppX & party! 

**Comment by rednoah** [comment]
I've never even heard of `makepri` so not doing step 4 and 5 is the probable culprit here.

Here's a thread in the MDSN forums:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/dc505f68-d120-43e3-a9e1-d7c77746d588/uwpdesktop-bridgeunplated-taskbar-icons-in-desktop-bridge-apps?forum=wpdevelop
