### ISSUE TITLE
Package acceptance validation error: Apps converted with the Desktop Bridge and that require the .NET Native framework must be pre-compiled by the .NET Native tool chain.

### ISSUE THREAD

**Issue by galich** [Microsoft/DesktopBridgeToUWP-Samples#27]
Trying to follow [guide here (Migrate step)](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net) and using [this sample](https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/AppServiceBridgeSample), I'm getting following error when uploading to the Store

> Package acceptance validation error: Apps converted with the Desktop Bridge and that require the .NET Native framework must be pre-compiled by the .NET Native tool chain.

Is there a way to upload to Store?

**Comment by wickste** [comment]
Yes, be sure to follow the steps precisely for creating an acceptable appxupload file manually. Then it will be accepted by the Store.


“To create the new appxupload file, we will create a new zip archive to include the generated appxsym and appxbundle from the _Test folder. Create a new zip file that contains the appxsym and appxbundle files, and then rename the extension to appxupload”

Thanks,
Stefan Wick

**Comment by galich** [comment]
@wickste aw, i totally missed that bit, let me give it a try, thank you

**Comment by galich** [comment]
confirmed, manual repackaging helps to get sample uploaded to the Store, thank you Stefan!

now it's time to try with the real app...

**Comment by galich** [comment]
perfect, while I hope tooling will get better to avoid all these manual steps, it works and 1Password lives 👍

**Comment by wickste** [comment]
Glad to hear it worked – congratulations!

Tooling improvements are high on our list for a future update.

Sent from my Windows 10 phone
