### ISSUE TITLE
Windows 10 SDK 10.0.14342.0

### ISSUE THREAD

**Issue by AddressXception** [Microsoft/DesktopBridgeToUWP-Samples#3]
Where can I get Windows 10 SDK 10.0.14342.0?

Unless Im missing something, Insider Preview page still only has a link for 

Windows 10 SDK 10.0.14332.0

Wont let me build without it.

Thx!

**Comment by vladimp** [comment]
Hi,

Thanks for your feedback!
I updated the samples to work against 14332 that is currently available.

Regards,
Vlad

**Comment by AddressXception** [comment]
Awesome!  It works now.  thanks!
