### ISSUE TITLE
Element Not Found

### ISSUE THREAD

**Issue by Mimetis** [Microsoft/DesktopBridgeToUWP-Samples#38]
Hi team !

I have an error, when trying to run the ``HelloWorldConsoleSample` application

The error occurs on runtime on the `TileUpdateManager.CreateTileUpdaterForApplication()` method
The exception is :
```
System.Exception: 'Element not found. (Exception from HRESULT: 0x80070490)'

```
Actually, I have the last VS 2017 (version 15.2 (26430.6)) installed.
I have installed the last Windows 10 SDK as well.

And I have no InnerException ...

**Comment by wickste** [comment]
You need to run this as packaged app, i.e. create an .appx package and deploy that first before running.

The error suggests that you might be running the .EXE directly, without packaging it as a Desktop Bridge app.

Thanks,
Stefan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
