### ISSUE TITLE
AppServiceConnection with winform client

### ISSUE THREAD

**Issue by yxylpj** [Microsoft/DesktopBridgeToUWP-Samples#4]
Hello

When i call AppService on UWP app, the AppServiceConnectionStatus returns Success.
But, when i call AppService on winform or wpf client, the AppServiceConnectionStatus still return AppServiceUnavailable.

How can I solve this issue?

My sample project [https://setup.aserweb.com/AppServiceSample.zip](url)

Thanks a lot.

**Comment by vladimp** [comment]
Hi!

AppServiceUnavailable means that the app with the specified package family name is installed and available, but the app does not declare support for the specified app service. Check that the name of the app service and the version of the app are correct.
If you still have the issue please share your project again as currently it is unreachable.

Thanks!
Vlad

**Comment by vladimp** [comment]
Please let me know if you have any further issues.
I am closing this issues.

Thanks,
Vlad
