### ISSUE TITLE
can call UWP from win32 ?

### ISSUE THREAD

**Issue by tdtanvn** [Microsoft/DesktopBridgeToUWP-Samples#5]
I see a lot of example wrote by c#
can you make an example call from UWP from C++

**Comment by vladimp** [comment]
Hi!
Yes, we are working on it and will publish it soon.

Thanks,
Vlad

**Comment by vladimp** [comment]
We added the requested sample - https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/AppServiceBridgeSample_C%2B%2B
Hope it helps, closing the issue.

Thanks,
Vlad
