### ISSUE TITLE
Can't debug WinformsOutOfProcessWinRTComponent -- looking for Brokered Component alternative

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/DesktopBridgeToUWP-Samples#52]
I have a working Brokered Component along the lines of the MSFT article [here](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/brokered-windows-runtime-components-for-side-loaded-windows-store-apps). I have also read Adam Braden's recent post "Calling WinRT Components from a Win32 process via the Desktop Bridge" [here](https://blogs.windows.com/buildingapps/2017/07/06/calling-winrt-components-win32-process-via-desktop-bridge/#qcSVUyuBhiYMeuLA.97), which references the WinformsOutOfProcessWinRTComponent sample.

I have built the sample but get an error: "The application appears to already be running" when trying to launch for debug. This is with VS 2017 15.4.0 Preview 1.0 and SDK 16210. I have tried killing the COM Surrogate, and even rebooting, to no avail.

The sample isn't quite my use case however, and uses a hand-rolled COM DLL. I am ultimately looking for is some sample or walk-though that consists of:

- A UWP C# application containing the UX inside the app container
- A WRT C++/CX component containing some non-UX application logic that runs outside the app container "full trust"

A WRT component running outside the sandbox that returned "hello" from a method would do.

The app won't be in the store, because the WRT component requires verboten win32 calls. How might I achieve this? The article mentions "metadata marshalling" but it is commented out in the appxmanifest [here](https://github.com/Microsoft/DesktopBridgeToUWP-Samples/blob/master/Samples/WinformsOutOfProcessWinRTComponent/WinFormsOOPWinRTComponent.Package/package.appxmanifest#L37). I think the pieces are there, but I am having trouble putting them together. Any help appreciated.

**Comment by wickste** [comment]
With the desktop bridge in Windows 10 we now have a better solution for this type of scenario. You can actually maintain both the UWP part and the fulltrust part in the same appx package – and you can have it all distributed and updated through the Windows Store. The communication between the two parts of the package is typically handled with an AppServiceConnection.

We have a couple of examples up in our repo for this. Let me know if you have any questions.

https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/AppServiceBridgeSample

https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/AppServiceBridgeSample_C%2B%2B

https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/SQLServer

https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/UWP%20Office%20Interop

https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/UWP%20Systray

Thanks,
Stefan Wick

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 16275 - 16.0.8500.4065]

**Comment by therealkenc** [comment]
I looked at using an AppServiceConnection before fighting my way through the "Brokered Windows Runtime Components for a side-loaded Windows Store app" article and getting the [template](https://marketplace.visualstudio.com/items?itemName=vs-publisher-713547.BrokeredWinRTComponentProjectTemplates) from for Visual Studio 2013 up on 2017. 

The ValueSet API isn't rich enough for my purposes. It's a "real" WRT component with TypedEventHandlers and the like. Maybe I mis-read what AppServiceConnection can do based on the samples. Please let me know if I have. But at base I am passing around WRT COM objects. Trying to wrap and unwrap those class methods into ValueSets would be a step backwards from the Brokered Component I already have up and running.

My question is whether I can improve on my Brokered Component using "Metadata Based Marshalling (MBM)". Googling the term does get me much in the way of hits. Right now I am building proxy stubs "by hand".

Am I better off just sticking with the 2013 solution, or can my workflow (if not the component itself) be improved with the features in SDK 16257? The section headline of the [article](https://blogs.windows.com/buildingapps/2017/07/06/calling-winrt-components-win32-process-via-desktop-bridge/#comment-27046#aFdVwwj5Lf3f1HiK.97) reads: "Metadata Based Marshaling – No more Proxy/Stub DLLs!" So I'm sold on the headline but don't know how to use it.

Right now my appxmanifest looks like:
```
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>clrhost.dll</Path>
        <ActivatableClass ActivatableClassId="MyBrokeredComponent.MyService" ThreadingModel="MTA">
          <ActivatableClassAttribute Name="DesktopApplicationPath" Type="string" Value="C:\Users\there\source\repos\BrokeredComponent\Debug" />
        </ActivatableClass>
      </InProcessServer>
    </Extension>
```

But I have to register the dll with regsrv32 and go though the whole [`mdmerge`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh869899%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) business to get a consumable winmd. Has this process improved? Maybe I was reading too much hope into the article?

**Comment by therealkenc** [comment]
@wickste - Okay I have struggled with the for a week but am no further. Rather than get bogged down in Brokered Component, maybe just the baby step of getting the [WinformsOutOfProcessWinRTComponent](https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/WinformsManagedWinRTComponent) _running_ will be a start, and we can worry about where I am trying to get to after. [Where I am trying to get to is marshal WRT objects between a UWP app and a Full Trust WRT server component.]

Trying to run the sample under Visual Studio 15.4.0 Preview 1 and SDK 10.0.16267.0 I get:
```
`Unable to activate Windows Store app 'c0f91aa6-1012-4d95-a8do-588a6f5fe6d1_4sdaedqydyjdm!WinFormsOOPWinRTComponenet'`.

The application appears to already be running. Close the application, and start debugging again
```
I have tried killing the COM Surrogate process with procexp64 (which dies on it's own anyway). I have even tried rebooting. This sample is only two months old and is the subject of this [blog post](https://blogs.windows.com/buildingapps/2017/07/06/calling-winrt-components-win32-process-via-desktop-bridge/#kimTUFfrX3mhC4L5.97) by Adam Braden.

Any help would be appreciated because I am hard blocked at the moment.
<br><br>

![winformsoutofprocesswinrtcomponent-fail-sept-1-2017](https://user-images.githubusercontent.com/7049700/29992722-55d5f604-8f57-11e7-843c-6b4273dadee3.png)

**Comment by wickste** [comment]
Adding Adam, the sample owner to help resolve this error.

Sent from my Windows 10 phone

**Comment by therealkenc** [comment]
@wickste @AdamBraden I managed to get a spiritual equivalent of the sample running with the [Windows Application Packaging Project](https://blogs.msdn.microsoft.com/appconsult/2017/08/28/package-a-net-desktop-application-using-the-desktop-bridge-and-visual-studio-preview/) per Matteo Pagani's recent [article](https://blogs.msdn.microsoft.com/appconsult/2017/08/28/package-a-net-desktop-application-using-the-desktop-bridge-and-visual-studio-preview/). I put the result on [github](https://github.com/therealkenc/WinformsOutOfProcessWinRT) just to stash it somewhere. Perhaps the sample broke with the recent SDK updates. Or perhaps I am missing something obvious that causes the `"...application appears to already be running.."` error above.

Unfortunately, having got the sample (or something like it) running, I have run headlong into back to my basic question. Adam's article states:
> The server must be registered for use by the AppContainer processes, or for use by the FullTrust processes. 

Okay, but then how do I marshal WinRT objects (interfaces) which perform verboten operations in and out of the AppContainer, like I am presently doing with my [Brokered WinRT Component](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/brokered-windows-runtime-components-for-side-loaded-windows-store-apps)? I have no legacy code here; I would prefer to use new UWP UX elements.

Anyway, enjoy the long weekend all. Until next week.

**Comment by AdamBraden** [comment]
The current sample for WinformsOutOfProcessWinRTComponent, does not include the Debugging project which is required if you want to F5.  Its goal was to show how to build and deploy one.  Since the sample was created, the new Windows Application Packaging project has come out that combines both packaging and debugging - this is a better solution and I'm glad you've discovered this and gotten it up and running with the sample.

Regarding your ultimate goal, however, we do not allow direct IPC between a FullTrust process and an AppContainer process.  This needs to be brokered through AppServices.  This is explicitly blocked in the platform layer because there are a lot of challenges in mixing the differences between the two models.  For the Desktop Bridge, this may be the last part of your app that you'd migrate - once the client and components can move to UWP/AppContainer.

**Comment by therealkenc** [comment]
Thanks @AdamBraden 

I have looked at the NorthwindSample. Yes you can encapsulate a data model in JSON. But how do I data bind a UWP UX element to the other side which has a `Windows::Foundation::Collections::ObservableVector<T>`? I could (in my head) imagine writing some kind of dispatch system on top of AppServices. "RPC on AppService". But that would be nuts...

To underline, I am not _migrating_ anything. They only reason I used a Brokered Component in the first place is I didn't want to do a green pasture project on a "legacy" UX platform.

Can you elaborate on the "challenges in mixing the differences between the two models"? If it helps to visualise, assume **both** the AppContainer part (which has Windows::UI::Xaml::Application) and the "system" bits are all written in C++/CX. Or WRL for that matter.

Or perhaps asking the question a different way: How does Microsoft do it? Sure as heck not by passing JSON back and forth. Perhaps I am missing something fundamental?

**Comment by wickste** [comment]
What is the functionality provided by your fulltrust component? Have you looked into moving it into the AppContainer? (which would eliminate the need for IPC in the first place).

Thanks,
Stefan

**Comment by therealkenc** [comment]
> What is the functionality provided by your fulltrust component?

@wickste - Yes I expected that question was coming. If I could work inside the App Container, I would of course.

Let's use a Microsoft project as an example. My use case is similar but unrelated. The Microsoft [Git Virtual File System](https://github.com/Microsoft/GVFS). Did they use WinRT to interface their driver? Did they use C++/CX? Nope. They used C++/CLI. It is not a "legacy" project in any sense. The thing isn't even a year old. They could marshal a filesystem over AppService in theory. No one would do that.

For my project, the most glaring problem is I need to call [`ZwSetEaFile()`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff961908%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) per this [Dev Center post](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/8f4a7650-1dd9-4a5c-bb38-7d33c16e16ef/uwpgettingsetting-ntfs-extended-attributes-in-uwp-app-ntqueryeafile-ntseteafile?forum=wpdevelop). They sent me here. I also need to write to `HKEY_CURRENT_USER`, because it is used for 'IPC' by a third party not in my control. That third party is Microsoft, but it could be anyone; the point is you can't "migrate" code that isn't yours. But the registry part is trivial so let's set that aside.

Given that I need to marshal something as complicated and performance sensitive as a filesystem, how do I do it? And, again, at least for my edification, how do _you_ do it?
