### ISSUE TITLE
AppServiceBridgeSample doesn't work with final Windows 10 AU build and SDK

### ISSUE THREAD

**Issue by smaillet-ms** [Microsoft/DesktopBridgeToUWP-Samples#7]
Tried loading this solution with the Windows 10 AU SDK and got errors about missing components (from a different build SDK I don't have installed). After manually editing the UWP csproj file to change the version numbers to the AU release number (14393) it was able to load, however the background app fails with:

~~An exception of type 'System.InvalidOperationException' occurred in BackgroundProcess.exe but was not handled in user code~~

~~Additional information: The process has no package identity. (Exception from HRESULT: 0x80073D54)~~

~~This occurs on the following line:
connection.PackageFamilyName = Windows.ApplicationModel.Package.Current.Id.FamilyName;~~

Scratch that, the second part came from the fact that when the UWP project didn't load initially VS set the background app as the startup project so when I hit F5 it tried to run as a normal Win32 app instead of launching the UWP app which would then start the background app. So there's only one issue here and that's the build numbers in the UWP.csproj file need to be updated to the final RTM.

**Comment by totht91** [comment]
Fixed. :)
