### ISSUE TITLE
Unclear code in NorthwindSample/NorthwindCent/UwaClient/App.xaml.cs

### ISSUE THREAD

**Issue by davidboschwitz** [microsoft/DesktopBridgeToUWP-Samples#96]
Is there a case where this [if statement](https://github.com/microsoft/DesktopBridgeToUWP-Samples/blob/master/Samples/NorthwindSample/NorthwindCent/UwaClient/App.xaml.cs#L61) would return false? If `details` (aka `args.TaskInstance.TriggerDetails`) was null, it should return false in the if statement on [line 55](https://github.com/microsoft/DesktopBridgeToUWP-Samples/blob/master/Samples/NorthwindSample/NorthwindCent/UwaClient/App.xaml.cs#L55). 

If so, including [this if statement](https://github.com/microsoft/DesktopBridgeToUWP-Samples/blob/master/Samples/NorthwindSample/NorthwindCent/UwaClient/App.xaml.cs#L61) is unnecessary and I think it leads people to create code that misuses the `is` operator.

**Comment by ptorr-msft** [comment]
Your analysis is correct; the code could just move to the new pattern-matching `is` operator. I will see if we can fix this. 

Can you elaborate on how it causes people to misuse the `is` operator?
